name: harukanew
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  http: ^1.1.0
  floating_bottom_navigation_bar: ^1.5.2
  syncfusion_flutter_datagrid: ^23.2.4
  url_launcher: ^6.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

